name: Build and Deploy

on:
  - push
  - pull_request

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: n1vanvol
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: dfbded1b59451f890bf2e9ace66575161fe3ee30f357fb0c6872cb836a439f88
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v4
      
      - name: Meow
        run: echo "hello"
      - name: Install python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install requirements.txt
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest -v -s