name: Build and Deploy

on:
  - push
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v4
      
      - name: Meow
        run: echo "hello"
      - name: Install python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install requirements.txt
        run: pip install -r requirements.txt
